"""Type stubs for rsplitcap native module."""

from typing import List, Optional

class Packet:
    ts_sec: int
    ts_usec: int
    length: int
    orig_len: int
    @property
    def ts(self) -> float: ...
    @property
    def data(self) -> bytes: ...

class Flow:
    @property
    def id(self) -> int: ...
    @property
    def proto(self) -> int: ...
    @property
    def proto_name(self) -> str: ...
    @property
    def src_addr(self) -> str: ...
    @property
    def dst_addr(self) -> str: ...
    @property
    def src_port(self) -> int: ...
    @property
    def dst_port(self) -> int: ...
    @property
    def packet_count(self) -> int: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def start_ts(self) -> float: ...
    @property
    def end_ts(self) -> float: ...
    def packets(self) -> List[Packet]: ...

class Archive:
    @property
    def flow_count(self) -> int: ...
    @property
    def link_type(self) -> int: ...
    @staticmethod
    def open(path: str) -> "Archive": ...
    def flows(self) -> List[Flow]: ...
    def get_flow(self, flow_id: int) -> Optional[Flow]: ...
    def find_by_ip(self, ip_str: str) -> List[Flow]: ...
    def find_by_port(self, port: int) -> List[Flow]: ...
    def find_by_protocol(self, proto_str: str) -> List[Flow]: ...

def create_archive(
    input_path: str,
    output_path: str,
    strategy: str = "session",
    max_sessions: int = 10000,
    ip_filters: List[str] = [],
    port_filters: List[int] = [],
) -> None: ...

def read_flows(
    input_path: str,
    strategy: str = "session",
    max_sessions: int = 10000,
    ip_filters: List[str] = [],
    port_filters: List[int] = [],
) -> Archive:
    """Read a pcap/pcapng file directly, returning an Archive of all flows."""
    ...

def split(
    input_path: str,
    output_dir: str,
    strategy: str = "session",
    max_sessions: int = 10000,
    buffer_bytes: int = 10000,
    ip_filters: List[str] = [],
    port_filters: List[int] = [],
    output_type: str = "pcap",
) -> None: ...

def pipe_archive(archive_path: str) -> List[bytes]: ...
